spring.profiles.active: production
spring.cache.cache-names: vets

#server:
#  port: 8001
#
#
#eureka:
#  client: #客户端注册进eureka服务列表内
#    service-url:
#      defaultZone: http://47.99.138.113:8761/eureka
#  #       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#  instance:
#    instance-id: test-vet
#    prefer-ip-address: true     #访问路径可以显示IP地址
#
#petclinic.database: hsqldb
#spring:
#  datasource:
#    schema: classpath*:db/hsqldb/schema.sql
#    data: classpath*:db/hsqldb/data.sql
#  sleuth:
#    sampler:
#      percentage: 1.0
#  application:
#    name: vet
#
#spring.jpa.hibernate.ddl-auto: none
